apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server
spec:
  replicas: 3 # Number of pods you want to run
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
    spec:
      containers:
        - name: edge-server
          image: gcr.io/even-cirrus-440703-d8/edge-server:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
